files = {'mexGPUcublas'};
cmd1 = ['/usr/local/cuda-12.3/bin/nvcc -c --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE' ...
        ' -I"/usr/local/cuda-12.3/include"' ...
        ' -I"/usr/local/MATLAB/R2022a/extern/include"' ...
        ' -I"/usr/local/MATLAB/R2022a/simulink/include"' ...
        ' -I"/usr/local/MATLAB/R2022a/toolbox/parallel/gpu/extern/include/"' ...
        ' -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70  -gencode arch=compute_80,code=sm_80' ...
        ' -std=c++11 --compiler-options=-ansi,-fexceptions,-fPIC,-fno-omit-frame-pointer,-lcufft,-lcufftw,-lcublas,-pthread -O0 -DNDEBUG' ...
        ' ' files{1} '.cu -o ' files{1} '.o'];

cmd2 = ['/usr/bin/g++ -pthread -Wl,--no-undefined -Wl,--no-as-needed -shared -O' ...
        ' -Wl,--version-script,"/usr/local/MATLAB/R2022a/extern/lib/glnxa64/mexFunction.map"' ...
        ' ' strcat(files{1},'.o') ' -ldl' ...
        ' /usr/local/cuda-12.3/targets/x86_64-linux/lib/libcusparse.so' ... % -lcusparse
        ' /usr/local/cuda-12.3/targets/x86_64-linux/lib/libcublas_static.a' ... % -lcublas_static
        ' /usr/local/cuda-12.3/targets/x86_64-linux/lib/libcusparse_static.a' ... % -lcusparse_static
        ' /usr/local/cuda-12.3/targets/x86_64-linux/lib/libculibos.a' ... % -lculibos'
        ' -L/usr/local/cuda-12.3/lib64 -Wl,-rpath-link,/usr/local/MATLAB/R2022a/bin/glnxa64' ...
        ' -L"/usr/local/MATLAB/R2022a/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -lmwgpu -lcufft -lcufftw -lcublas -lcublasLt' ...
        ' /usr/local/cuda-12.3/targets/x86_64-linux/lib/libcudart.so' ... % /usr/local/MATLAB/R2016a/bin/glnxa64/libcudart.so.7.5
        ' -o ' files{1} '.mexa64'];

system(cmd1);
system(cmd2);

A = rand(1000, 4000); % Example matrix A
x = rand(4000, 1); % Example vector x
y = mexGPUblasexample(A, x);
