files = {'mexGPUcublas'};
cmd1 = ['/usr/local/cuda-13.1/bin/nvcc -c --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE' ...
        ' -I"/usr/local/cuda-13.1/include"' ...
        ' -I"/usr/local/MATLAB/R2025b/extern/include"' ...
        ' -I"/usr/local/MATLAB/R2025b/simulink/include"' ...
        ' -I"/usr/local/MATLAB/R2025b/toolbox/parallel/gpu/extern/include/"' ...
        ' -gencode arch=compute_80,code=sm_80 -gencode arch=compute_89,code=sm_89' ...
        ' -std=c++11 ' ...
        ' -Xcompiler "-fexceptions -fPIC -fno-omit-frame-pointer -pthread" ' ...
        ' -O2 -DNDEBUG ' ...
        ' ' files{1} '.cu -o ' files{1} '.o'];

cmd2 = ['/usr/bin/g++ -pthread -Wl,--no-undefined -Wl,--no-as-needed -shared -O' ...
        ' -Wl,--version-script,"/usr/local/MATLAB/R2025b/extern/lib/glnxa64/mexFunction.map"' ...
        ' ' strcat(files{1},'.o') ' -ldl' ...
        ' /usr/local/cuda-13.1/targets/x86_64-linux/lib/libcusparse.so' ... % -lcusparse
        ' /usr/local/cuda-13.1/targets/x86_64-linux/lib/libcublas_static.a' ... % -lcublas_static
        ' /usr/local/cuda-13.1/targets/x86_64-linux/lib/libcusparse_static.a' ... % -lcusparse_static
        ' /usr/local/cuda-13.1/targets/x86_64-linux/lib/libculibos.a' ... % -lculibos'
        ' -L/usr/local/cuda-13.1/lib64 -Wl,-rpath-link,/usr/local/MATLAB/R2025b/bin/glnxa64' ...
        ' -L"/usr/local/MATLAB/R2025b/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -lmwgpu -lcufft -lcufftw -lcublas -lcublasLt' ...
        ' /usr/local/cuda-13.1/targets/x86_64-linux/lib/libcudart.so' ... % /usr/local/MATLAB/R2016a/bin/glnxa64/libcudart.so.7.5
        ' -o ' files{1} '.mexa64'];

system(cmd1);
system(cmd2);

A = rand(10000, 10000); % Example matrix A
x = rand(10000, 1); % Example vector x
tic
y = mexGPUcublas(A, x);
toc
